# Generated by Django 4.1.4 on 2022-12-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_created_alter_location_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cleaning_state',
            field=models.CharField(blank=True, choices=[(1, 'Not Cleaned'), (2, 'Cleaning'), (3, 'Cleaned')], max_length=15, null=True),
        ),
    ]
