# Generated by Django 4.1.7 on 2023-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
